import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Products from './Products.json';
import Prod from './prod'
import ProductsPage from "./Productspage"
import  DatoCMSPlugin  from "./datoCmo"


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <link rel="preconnect" href="https://app.snipcart.com" />
      <link rel="preconnect" href="https://cdn.snipcart.com" />
      <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      
        <title>Online Gaming Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className='heading'>
            E-Commerce
            {/* <code className={styles.code}>src/pages/index.tsx</code> */}
          </h1>
          <div>
            <a
              href="https://www.amazon.in/s?k=-amazon&hvadid=72499124504037&hvbmt=be&hvdev=c&hvqmt=e&tag=msndeskstdin-21&ref=pd_sl_5fksc5jb1x_e"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/aicon.png"
                alt="amazon Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/Amazon-Logo.png"
            alt="amazon Logo"
            width={180}
            height={80}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={50}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
        {Products.map(Product => {
    return (
      <div key={Product.id} className={styles.card}>
        <img src={Product.image} alt={`Preview of ${Product.title}`} />
        <h3>{ Product.title }</h3>
        <p>{ Product.description }</p>
        <p>${ Product.price }</p>
        <p>
        <button className="snipcart-add-item"
          data-item-id={Product.id}
          data-item-image={Product.image}
          data-item-name={Product.title}
          data-item-price={Product.price}
>
          Add Item to Cart
        </button>
        </p>
      </div>
    );
  })}
        </div>
      </main>
      <footer className={styles.footer}>
      <script async src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />

      <div hidden id="snipcart" data-api-key="ZDhkNGFlMTctZmRiZS00YmYyLWJiOWEtOTQ0ZWVhYThkNjQ1NjM4MTMxMDI4Nzg5MzAyNjM4" />
      <h1>More Details:</h1>
      <div>
      <a href="https://www.playstation.com/en-in/ps4/"><u>Click on here</u></a>
      </div>
      <h1>Reviews:</h1>
        <div>
          1.Exellent
          2.Good
          3.Just Perfect 
          4.Not Worth it
        </div>
      
        <a
          href="https://www.amazon.in/s?k=-amazon&hvadid=72499124504037&hvbmt=be&hvdev=c&hvqmt=e&tag=msndeskstdin-21&ref=pd_sl_5fksc5jb1x_e"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img src="/Amazon-Logo.png" alt="Amazon Logo" className={styles.logo} />
        </a>
      </footer>
    </>
  )
}
